name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking time to report a bug.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / recordings
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: Browser, OS, device
